server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  ## git配置时使用
#    config:
#      server:
#        git:
#          uri:
#          username:
#          password:
  ##本地配置使用
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka